#!/bin/bash



s1="mci1.btaks.com"
s2="mci.btaks.com"
s3="mci.bcdnpro.com"
s4="s22.biovdns.com"
s5="s23.biovdns.com"
s6="s24.biovdns.com"
s7="s25.biovdns.com"
s8="s26.biovdns.com"
s9="s27.biovdns.com"
s10="s28.biovdns.com"
s11="s29.biovdns.com"
s12="s30.biovdns.com"
s13="s31.biovdns.com"
s14="s32.biovdns.com"
s15="s33.biovdns.com"
s16="s34.biovdns.com"
s17="s35.biovdns.com"
s18="s36.biovdns.com"
s19="static.221.61.108.65.clients.your-server.de"
echo "please enter number of the server you want (1-18):"
read num

#switch=s${num}

#server=""

case $num in
1)
	server="mci1.btaks.com"
	;;

2)
	server="mci.btaks.com"
	;;

3)
	server="mci.bcdnpro.com"
	;;
4)
	server="s22.biovdns.com"
	;;
5)
	server="s23.biovdns.com"
	;;
6)
	server="s24.biovdns.com"
	;;
7)
	server="s25.biovdns.com"
	;;
8)
	server="s26.biovdns.com" 
	;;
9)
	server="s36.biovdns.com"
	;;
10)
	server="s27.biovdns.com"
	;;
11)
	server="s28.biovdns.com"
	;;
12)
	server="s29.biovdns.com"
	;;
13)
	server="s30.biovdns.com"
	;;
14)
	server="s31.biovdns.com"
	;;
15)
	server="s32.biovdns.com"
	;;
16)
	server="s33.biovdns.com"
	;;
17)
	server="s34.biovdns.com"
	;;
18)
	server="s35.biovdns.com"
	;;
19)
	server="static.221.61.108.65.clients.your-server.de"
esac



sudo openconnect $server  --no-dtls

